version: '3'

services:
  scraper:
    build: .
    ports:
      - "9600:9600"
    restart: unless-stopped
    environment:
      - FETCH_INTERVAL=60

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - scraper
    restart: unless-stopped
